server.port: 8080
spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/gestaoDePedidos"
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

