server.port: 8080
spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/gestaoDePedidos"
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"


mercado:
  pago:
    client:
      url: https://api.mercadopago.com/instore/orders/qr/seller/collectors
      authToken: Bearer TEST-4111707035331742-082310-03df9d668e959289b710b132f1f2bccd-479782134
      userId: 479782134
      externalPosId: SUC001POS001