server.port: 8080
spring:
  data:
    mongodb:
      user: ${MONGO_USERNAME:""}
      password: ${MONGO_PASSWORD:""}
      database: ${MONGO_DB:gestaoDePedidos}
      uri: mongodb+srv://${spring.data.mongodb.user}:${spring.data.mongodb.password}@fastfood-management-clu.d9zacsh.mongodb.net
      port: 27017

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      enabled: true
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true


mercado:
  pago:
    client:
      url: https://api.mercadopago.com/instore/orders/qr/seller/collectors
      authToken: ${MP_PAYMENT_TOKEN}
      userId: ${MP_USER_ID}
      externalPosId: ${MP_EXTERNAL_POS_ID}

jwt:
  # secret: ${JWT_TOKEN_SECRET}
  secret: jwt-secret
