apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-configmap
data:
  MONGO_HOST: fastfood-mongo-service
  MONGO_USERNAME: tech-challenge
  MONGO_PASSWORD: tech-challenge-123
  MONGO_DB: gestaoDePedidos
