name: Deploy ECS

on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
    
    - name: Configurando credenciais AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
        
    - name: Get Task File
      run: aws ecs describe-task-definition --task-definition fastfood-management-task --query taskDefinition > task-definition.json

  
